server:
  port: 8081

spring:
  application:
    name: keycloak-with-openid-connect
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: keycloak-with-openid-connect
            client-secret: YophioB3OgkR9xlQCD1nauWHbYm4BIGh
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/myrealm